SET SCHEMA R;

-- app setup

CREATE VIEW R_KM_DATA AS
 SELECT ID, LIFESPEND, NEWSPEND, INCOME, LOYALTY
  FROM CUSTOMERS
  ;

CREATE COLUMN TABLE R_KM_RESULTS (ID BIGINT NOT NULL, CLUSTERNUMBER INTEGER);

-- R setup
CREATE PROCEDURE R_KM (IN data R_KM_DATA, OUT results R_KM_RESULTS)
LANGUAGE RLANG AS 
BEGIN
	library(cluster)
	clusters <- kmeans(data[c('LIFESPEND','NEWSPEND','INCOME','LOYALTY')], 3)
	results <- cbind(data[c('ID')], CLUSTERNUMBER=clusters$cluster)
END;

-- app runtime

TRUNCATE TABLE R_KM_RESULTS;

CALL R_KM (R_KM_DATA, R_KM_RESULTS) WITH OVERVIEW;

SELECT * FROM R_KM_DATA;
SELECT * FROM R_KM_RESULTS;
