-- results inline

CALL "R_CLUSTER" ("DATA", "PARAMS", "RESULTS") WITH OVERVIEW WITH HINT(SQLSCRIPT_PLAN_PROFILER);


-- results stored

ALTER SYSTEM START SQLSCRIPT PLAN PROFILER FOR PROCEDURE "RUSER"."R_CLUSTER";

ALTER SYSTEM CLEAR SQLSCRIPT PLAN PROFILER FOR PROCEDURE "RUSER"."R_CLUSTER";

ALTER SYSTEM STOP SQLSCRIPT PLAN PROFILER FOR PROCEDURE "RUSER"."R_CLUSTER";

SELECT * FROM "M_SQLSCRIPT_PLAN_PROFILERS";

SELECT * FROM "M_SQLSCRIPT_PLAN_PROFILER_RESULTS";
