DROP SCHEMA R CASCADE;

CREATE SCHEMA R;

SET SCHEMA R;

CREATE COLUMN TABLE "CUSTOMERS" (
	 "ID" BIGINT NOT NULL,
	 "CUSTOMER" NVARCHAR(60),
	 "LIFESPEND" DOUBLE,
	 "NEWSPEND" DOUBLE,
	 "INCOME" DOUBLE,
	 "LOYALTY" DOUBLE,
	 PRIMARY KEY ("ID"))
	 ;
