SET SCHEMA R;

IMPORT FROM CSV FILE '/tmp/R/CUSTOMERS.csv' 
	   INTO "CUSTOMERS" 
       WITH COLUMN LIST IN FIRST ROW RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',' OPTIONALLY ENCLOSED BY '"' ERROR LOG 'CUSTOMERS.err' TABLE LOCK
       ;
